version: 2

jobs:
  test:
    docker:
      - image: node:10.15-alpine
    steps:
      - checkout

      - run: npm install

      - run:
          name: Run tests
          command: |
            npm run test

  deploy:
    docker:
      - image: node:10.15-alpine
    steps:
      - checkout

      - run:
          name: Publish package
          command: npm publish --userconfig=.npmrc-auth

  buildImage:
    docker:
      - image: web3f/ci-commons:v0.1.9
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            /scripts/build-image.sh web3f/polkadot-deployer .

workflows:
  version: 2
  test-deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - buildImage:
          filters:
            branches:
              only: /master/
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
