image:
  repo: parity/polkadot
  tag: v0.4.4

initImage:
  repo: web3f/polkadot-deployer
  tag: latest

chainspec:
  custom: true
  createConfigmap: false
  path: "/chainspec/chainspec.json"

mainNode: false

mainNodeID: QmQZ8TjTqeDj3ciwr93EJ95hxfDsb9pEYDizUAbWpigtQN
nodeKey: "0000000000000000000000000000000000000000000000000000000000000001"

validator: true

resources: {}
#  requests:
#    memory: "5Gi"
#    cpu: "1.5"

persistence:
  enabled: false
  dataSize: 32Gi
  chainspecSize: 10Mi
  storageClassName: standard
  accessModes: [ "ReadWriteOnce" ]
